name: input-job
on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'My input value'
        default: 'hello world'
        required: false  # This must be either true or false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print input value
        run: echo "Input value:${{ github.event.inputs.my_input }}"
